### ISSUE TITLE
Advantages/Disadvantages InfluxDB and CouchDB/PouchDB

### ISSUE THREAD

**Issue by JaromirCharles** [blackbox-dev/blackbox#11]

**Comment by GITBSB** [comment]
| | CouchDB/Pouch| Influx|
| :-- | :---: | :---: |
| Description | Documents with Json structure | Time-based with timestamp |
| Data | easy to store other data types (like plain text) | time series, events and metrics  |
| Query | javaScript for MapReduc on views | SQL-like query language - more powerful and faster for our uses: example history data (time > x and time < y)  |
| Other |  | scalable, fast to get data in and out |
| Sync | PouchDB:  store data locally while offline, then synchronize it with CouchDB when the application is back online - _pro_: Offline-first attempt,  fully functional offline mode _con_: client-heavy if you have to handle large data amounts  | write own sync - local caches (file) with sync on timestamp  or GraphQL? |
